import { NextResponse } from "next/server";
import { adminClient, authenticate, isAuthError } from "@/lib/apiAuth";

export async function POST(request: Request) {
  const caller = await authenticate(request);
  if (isAuthError(caller)) return caller;
  if (caller.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  let tutorId: number;
  try {
    const body = await request.json() as { tutorId?: unknown };
    if (typeof body.tutorId !== "number" || !Number.isInteger(body.tutorId)) {
      throw new Error("Invalid tutorId");
    }
    tutorId = body.tutorId;
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const admin = adminClient();

  // Verify the tutor exists and is not archived
  const { data: tutor, error: tErr } = await admin
    .from("tutors")
    .select("id, name")
    .eq("id", tutorId)
    .eq("archived", false)
    .single();
  if (tErr || !tutor) {
    return NextResponse.json({ error: "Tutor not found" }, { status: 404 });
  }

  // Create the preview session — token is generated by the DB
  const { data: preview, error: pErr } = await admin
    .from("admin_tutor_preview_sessions")
    .insert({ admin_id: caller.id, tutor_id: tutorId })
    .select("id, token, expires_at")
    .single();
  if (pErr || !preview) {
    return NextResponse.json({ error: "Failed to create preview session" }, { status: 500 });
  }

  // Log start event (token value is intentionally omitted from logs)
  console.log(`[preview] START admin=${caller.id} tutor=${tutorId} previewId=${preview.id}`);

  const st = preview as { id: number; token: string; expires_at: string };

  return NextResponse.json({
    previewId:  st.id,
    tutorName:  (tutor as { id: number; name: string }).name,
    expiresAt:  st.expires_at,
    previewUrl: `/portal/tutor?preview=${st.token}`,
  });
}
