import { NextResponse } from "next/server";
import { adminClient, authenticate, isAuthError } from "@/lib/apiAuth";

export async function POST(request: Request) {
  const caller = await authenticate(request);
  if (isAuthError(caller)) return caller;
  if (caller.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  let studentId: number;
  let viewAs: "student" | "parent" = "student";
  try {
    const body = await request.json() as { studentId?: unknown; viewAs?: unknown };
    if (typeof body.studentId !== "number" || !Number.isInteger(body.studentId)) {
      throw new Error("Invalid studentId");
    }
    studentId = body.studentId;
    if (body.viewAs === "parent") viewAs = "parent";
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const admin = adminClient();

  // Verify the student exists and is not archived
  const { data: student, error: sErr } = await admin
    .from("students")
    .select("id, name")
    .eq("id", studentId)
    .eq("archived", false)
    .single();
  if (sErr || !student) {
    return NextResponse.json({ error: "Student not found" }, { status: 404 });
  }

  // Create the preview session — token is generated by the DB
  const { data: preview, error: pErr } = await admin
    .from("admin_preview_sessions")
    .insert({ admin_id: caller.id, student_id: studentId, view_as: viewAs })
    .select("id, token, expires_at")
    .single();
  if (pErr || !preview) {
    return NextResponse.json({ error: "Failed to create preview session" }, { status: 500 });
  }

  // Log start event (token value is intentionally omitted from logs)
  console.log(`[preview] START admin=${caller.id} student=${studentId} previewId=${preview.id}`);

  const st = preview as { id: number; token: string; expires_at: string };

  return NextResponse.json({
    previewId:   st.id,
    studentName: (student as { id: number; name: string }).name,
    expiresAt:   st.expires_at,
    previewUrl:  `/portal/student?preview=${st.token}`,
  });
}
